# -*- coding: utf-8 -*-
"""07-10-2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V8D17Qc8mDJ0SXp-XBGXGSXNfiQRpkFh
"""

!apt install build-essential portaudio19-dev

!pip install pyaudio

!pip3 install SpeechRecognition pydub

import speech_recognition as sr

r = sr.Recognizer()

f1 = "r6.wav"
f2="r7.wav"

import IPython.display as ipd
(ipd.Audio(f1))

#using microphone 
with sr.Microphone() as source2:
    # listen for the data (load audio to memory)
    audio_data2 = r.listen(source2)
    # recognize (convert from speech to text)
    text3 = r.recognize_google(audio_data2)
    print(text3)

#using audiofile
with sr.AudioFile(f1) as source:
    # listen for the data (load audio to memory)
    audio_data = r.record(source)
    # recognize (convert from speech to text)
    text1 = r.recognize_google(audio_data)
    print(text1)

"""WITH MICROPHONE"""

#using microphone
with sr.Microphone() as source3:
    # listen for the data (load audio to memory)
    audio_data3= r.listen(source3)
    # recognize (convert from speech to text)
    text4 = r.recognize_google(audio_data3)
    print(text4)

#using audiofile
with sr.AudioFile(f2) as source1:
    # listen for the data (load audio to memory)
    audio_data1 = r.record(source1)
    # recognize (convert from speech to text)
    text2 = r.recognize_google(audio_data1)
    print(text2)

if text1==text2:
  print(text2)
else:
  print("Does not match")

